In [ ]:
#!pip install nb_black

In [ ]:
%load_ext nb_black

In [8]:
import cv2
import numpy as np

In [16]:

cap = cv2.VideoCapture(0)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

In [17]:


while True: 
    ret, frame = cap.read()
    #image_np = np.array(frame)

    #img = "IMG_20220617_094458"
    #frame = cv2.imread("C:/Users/Adnan/Pictures/Camera Roll/WIN_20220625_10_23_51_Pro.jpg".format(img))

    ### initialize aruco marker
    aruco_params = cv2.aruco.DetectorParameters_create()
    aruco_dict = cv2.aruco.Dictionary_get(cv2.aruco.DICT_4X4_50)
    aruco_coord, _, _ = cv2.aruco.detectMarkers(frame, aruco_dict, parameters=aruco_params)

    print(aruco_coord)

    cv2.polylines(frame, np.int64(aruco_coord), True, (255, 0, 0))
    
    cv2.imshow('ARUCO', cv2.resize(frame, (1500, 1200)))

    # see the results
    if cv2.waitKey(1) & 0xFF == ord('q'):
        cap.release()
        break

cv2.destroyAllWindows()


()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
(

()
()
(array([[[210., 116.],
        [315., 110.],
        [335., 166.],
        [229., 180.]]], dtype=float32),)
()
()
()
()
()
(array([[[278., 130.],
        [378., 125.],
        [407., 179.],
        [305., 193.]]], dtype=float32),)
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
(array([[[299., 436.],
        [295., 438.],
        [296., 415.],
        [298., 413.]]], dtype=float32),)
(array([[[299., 436.],
        [295., 438.],
        [296., 415.],
        [298., 413.]]], dtype=float32),)
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
(

()
()
()
()
()
()
()
()
()
()
()
()
(array([[[354., 248.],
        [439., 252.],
        [443., 319.],
        [344., 321.]]], dtype=float32),)
(array([[[355., 247.],
        [439., 252.],
        [443., 319.],
        [344., 321.]]], dtype=float32),)
()
()
()
()
()
()
()
(array([[[344., 250.],
        [429., 254.],
        [432., 320.],
        [335., 316.]]], dtype=float32),)
(array([[[340., 250.],
        [425., 254.],
        [428., 320.],
        [331., 316.]]], dtype=float32),)
(array([[[337., 250.],
        [421., 253.],
        [424., 320.],
        [328., 316.]]], dtype=float32),)
()
(array([[[331., 251.],
        [416., 254.],
        [419., 320.],
        [322., 317.]]], dtype=float32),)
()
()
()
(array([[[337., 245.],
        [421., 249.],
        [425., 315.],
        [328., 311.]]], dtype=float32),)
()
(array([[[340., 246.],
        [425., 248.],
        [429., 315.],
        [330., 318.]]], dtype=float32),)
()
()
()
()
(array([[[337., 242.],
        [422., 244.],
       

(array([[[300., 100.],
        [402.,  98.],
        [416., 181.],
        [299., 183.]]], dtype=float32),)
(array([[[299., 100.],
        [401.,  98.],
        [415., 182.],
        [299., 195.]]], dtype=float32),)
()
()
(array([[[299., 101.],
        [401.,  99.],
        [416., 182.],
        [299., 196.]]], dtype=float32),)
(array([[[299., 101.],
        [401., 100.],
        [416., 183.],
        [299., 197.]]], dtype=float32),)
(array([[[299., 101.],
        [401., 100.],
        [416., 183.],
        [299., 197.]]], dtype=float32),)
(array([[[299., 102.],
        [401., 100.],
        [415., 184.],
        [299., 197.]]], dtype=float32),)
()
(array([[[299., 102.],
        [401., 101.],
        [415., 184.],
        [299., 197.]]], dtype=float32),)
(array([[[299., 103.],
        [401., 101.],
        [415., 184.],
        [298., 185.]]], dtype=float32),)
(array([[[299., 103.],
        [401., 101.],
        [416., 184.],
        [299., 197.]]], dtype=float32),)
(array([[[300., 103

()
()
(array([[[285., 101.],
        [387.,  99.],
        [401., 182.],
        [285., 196.]]], dtype=float32),)
(array([[[285., 101.],
        [394., 108.],
        [401., 183.],
        [284., 185.]]], dtype=float32),)
(array([[[286., 101.],
        [388.,  99.],
        [402., 182.],
        [285., 196.]]], dtype=float32),)
()
()
(array([[[287., 102.],
        [396., 109.],
        [403., 183.],
        [286., 185.]]], dtype=float32),)
(array([[[287., 103.],
        [389., 100.],
        [404., 183.],
        [287., 197.]]], dtype=float32),)
(array([[[288., 102.],
        [390., 101.],
        [404., 183.],
        [287., 197.]]], dtype=float32),)
(array([[[288., 102.],
        [390., 100.],
        [404., 183.],
        [287., 185.]]], dtype=float32),)
()
(array([[[289., 103.],
        [391., 102.],
        [404., 184.],
        [288., 197.]]], dtype=float32),)
()
(array([[[290., 102.],
        [391., 101.],
        [405., 184.],
        [289., 197.]]], dtype=float32),)
(array([[[

()
(array([[[313., 119.],
        [409., 125.],
        [418., 204.],
        [308., 197.]]], dtype=float32),)
()
(array([[[313., 119.],
        [409., 125.],
        [418., 203.],
        [307., 196.]]], dtype=float32),)
(array([[[314., 118.],
        [410., 125.],
        [419., 203.],
        [308., 206.]]], dtype=float32),)
()
()
(array([[[311., 120.],
        [407., 126.],
        [416., 204.],
        [306., 197.]]], dtype=float32),)
(array([[[312., 120.],
        [408., 126.],
        [417., 204.],
        [306., 207.]]], dtype=float32),)
(array([[[313., 119.],
        [409., 126.],
        [418., 204.],
        [308., 196.]]], dtype=float32),)
(array([[[314., 118.],
        [410., 125.],
        [419., 203.],
        [309., 205.]]], dtype=float32),)
(array([[[313., 120.],
        [409., 126.],
        [418., 204.],
        [308., 207.]]], dtype=float32),)
(array([[[314., 119.],
        [410., 126.],
        [419., 204.],
        [310., 197.]]], dtype=float32),)
(array([[[315., 

()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
(

()
()
(array([[[212.,  99.],
        [276., 113.],
        [269., 180.],
        [214., 165.]]], dtype=float32),)
(array([[[212.,  99.],
        [276., 113.],
        [269., 180.],
        [214., 165.]]], dtype=float32),)
(array([[[213.,  99.],
        [276., 113.],
        [269., 180.],
        [214., 165.]]], dtype=float32),)
(array([[[213.,  99.],
        [276., 113.],
        [269., 180.],
        [214., 165.]]], dtype=float32),)
(array([[[212.,  99.],
        [276., 114.],
        [269., 180.],
        [214., 165.]]], dtype=float32),)
(array([[[212.,  98.],
        [276., 114.],
        [268., 180.],
        [214., 165.]]], dtype=float32),)
(array([[[212.,  98.],
        [276., 114.],
        [268., 180.],
        [214., 165.]]], dtype=float32),)
(array([[[212.,  99.],
        [276., 114.],
        [269., 180.],
        [214., 165.]]], dtype=float32),)
(array([[[212.,  98.],
        [276., 113.],
        [269., 179.],
        [214., 165.]]], dtype=float32),)
(array([[[212.,  98.],

(array([[[188.,  88.],
        [250., 101.],
        [246., 167.],
        [192., 154.]]], dtype=float32),)
(array([[[188.,  89.],
        [251., 103.],
        [246., 167.],
        [192., 154.]]], dtype=float32),)
(array([[[187.,  89.],
        [250., 101.],
        [246., 167.],
        [192., 154.]]], dtype=float32),)
(array([[[187.,  89.],
        [250., 101.],
        [246., 167.],
        [192., 154.]]], dtype=float32),)
()
(array([[[189.,  90.],
        [251., 104.],
        [247., 169.],
        [193., 156.]]], dtype=float32),)
(array([[[189.,  90.],
        [251., 103.],
        [247., 169.],
        [193., 156.]]], dtype=float32),)
(array([[[189.,  90.],
        [251., 103.],
        [247., 169.],
        [193., 156.]]], dtype=float32),)
(array([[[189.,  91.],
        [251., 103.],
        [247., 169.],
        [193., 156.]]], dtype=float32),)
(array([[[189.,  91.],
        [251., 103.],
        [247., 169.],
        [193., 156.]]], dtype=float32),)
(array([[[189.,  91.],
  

()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()


In [11]:
cap.release()

# Object classes

In [ ]:
class Hochregallager:
    def __init__(self):
        self.behaelter_obj_list = []
        self.behaelter_arr = [[None for i in range(3)] for j in range(3)]

    def add_behaelter(self, behaelter_obj):
        self.behaelter_obj_list.append(behaelter_obj)

    def check_for_missing_behaelter(self):
        # check if a behaelter was removed, if so - call remove
        pass

    def remove_behaelter(self):
        pass

In [ ]:
class WerkStueck:
    def __init__(self, box, score, color):

        # ymin, xmin, ymax, xmax = box
        self.bounding_box = box
        self.score = score
        self.color = color

In [ ]:
class Behaelter:
    def __init__(self, image, behaelter_box, behaelter_score, filtered_WerkStueck_detections):
        im_height = image.shape[0]
        im_width = image.shape[1]
        
        wkst_boxes, _, wkst_scores = filtered_WerkStueck_detections
        
        # ymin, xmin, ymax, xmax
        self.bounding_box = get_box_coordinates_from_normalized_coordinates(behaelter_box, im_height, im_width)
        self.werk_stueck = self.has_WerkStueck(wkst_boxes, wkst_scores, image, im_height, im_width)
        self.empty = True if self.werk_stueck is None else False

    def has_WerkStueck(self, wkst_boxes, wkst_scores, image, im_height, im_width):
        return bounding_box_intersect(self.bounding_box, wkst_boxes, wkst_scores, image, im_height, im_width)


# Intersect methods  

In [ ]:
def get_box_coordinates_from_normalized_coordinates(
    norm_box, im_height, im_width, return_int=False
):
    ymin, xmin, ymax, xmax = (
        norm_box[0] * im_height,
        norm_box[1] * im_width,
        norm_box[2] * im_height,
        norm_box[3] * im_width,
    )
    if return_int:
        ymin = int(ymin)
        xmin = int(xmin)
        ymax = int(ymax)
        xmax = int(xmax)
    return (ymin, xmin, ymax, xmax)


def one_dim_intersect(a0, a1, b0, b1):
    # a contains b
    if a0 < b0 and a1 > b1:
        intersect = b1 - b0
    # b contains a
    elif a0 >= b0 and a1 <= b1:
        intersect = a1 - a0
    # right part of a and left part of b intersect
    elif a0 < b0 and a1 > b0:
        intersect = a1 - b0
    # left part of a and right part of b intersect
    elif a1 > b1 and a0 < b1:
        intersect = b1 - a0
    # no intersect
    else:
        intersect = 0
    return intersect


def bounding_box_intersect(
    behaelter_box, wkst_boxes, wkst_scores, image, im_height, im_width
):
    b_ymin, b_xmin, b_ymax, b_xmax = behaelter_box
    behaelter_box_area = float((b_xmax - b_xmin) * (b_ymax - b_ymin))
    # using list to check for errors, only one elem should be appended
    intersect_elements = []

    # loop over all WerkStueck bounding boxes and find the corresponding one
    for i in range(wkst_boxes.shape[0]):
        (
            w_ymin,
            w_xmin,
            w_ymax,
            w_xmax,
        ) = get_box_coordinates_from_normalized_coordinates(
            wkst_boxes[i], im_height, im_width
        )
        intersect_width = one_dim_intersect(b_xmin, b_xmax, w_xmin, w_xmax)
        intersect_height = one_dim_intersect(b_ymin, b_ymax, w_ymin, w_ymax)
        intersect_area = intersect_width * intersect_height
        percent = intersect_area / behaelter_box_area
        # print(percent)
        if percent >= 0.2:
            intersect_elements.append(
                ((w_ymin, w_xmin, w_ymax, w_xmax), wkst_scores[i])
            )

    if len(intersect_elements) == 1:
        wkstk_box = intersect_elements[0][0]
        wkstk_score = intersect_elements[0][1]
        wkstk_color = detect_color_in_bounding_box(image, wkstk_box, False)

        wkstk = WerkStueck(wkstk_box, wkstk_score, wkstk_color)
        return wkstk

    else:
        if len(intersect_elements) > 1:
            print(
                "{} wkstk elements intersect behaelter:{}".format(
                    len(intersect_elements), behaelter_box
                )
            )
        return None

# Setup

In [ ]:
WORKSPACE_PATH = "Tensorflow/workspace"
SCRIPTS_PATH = "Tensorflow/scripts"
APIMODEL_PATH = "Tensorflow/models"
ANNOTATION_PATH = WORKSPACE_PATH + "/annotations"
IMAGE_PATH = WORKSPACE_PATH + "/images"
MODEL_PATH = WORKSPACE_PATH + "/models"
PRETRAINED_MODEL_PATH = WORKSPACE_PATH + "/pre-trained-models"
CONFIG_PATH = MODEL_PATH + "/my_ssd_mobnet/pipeline.config"
CHECKPOINT_PATH = MODEL_PATH + "/my_ssd_mobnet/"

In [ ]:
CUSTOM_MODEL_NAME = "my_ssd_mobnet"

In [ ]:
import tensorflow as tf
from object_detection.utils import config_util
from object_detection.protos import pipeline_pb2
from google.protobuf import text_format

In [ ]:
CONFIG_PATH = MODEL_PATH + "/" + CUSTOM_MODEL_NAME + "/pipeline.config"

In [ ]:
import os
from object_detection.utils import label_map_util
from object_detection.builders import model_builder

In [ ]:
# Load pipeline config and build a detection model
configs = config_util.get_configs_from_pipeline_file(CONFIG_PATH)
detection_model = model_builder.build(model_config=configs["model"], is_training=False)

# Restore checkpoint
ckpt = tf.compat.v2.train.Checkpoint(model=detection_model)
ckpt.restore(os.path.join(CHECKPOINT_PATH, "ckpt-21")).expect_partial()


@tf.function
def detect_fn(image):
    image, shapes = detection_model.preprocess(image)
    prediction_dict = detection_model.predict(image, shapes)
    detections = detection_model.postprocess(prediction_dict, shapes)
    return detections

# Color detection

COLOR DETECT - get color for single bounding box

In [ ]:
import numpy as np
import cv2

### COLOR THRESHOLDS
# 110 lower bounds to make sure white(/black) isn't mistakenly recognized
lower_sat = 110
lower_val = 110
upper_sat = 255
upper_val = 255

# RED
red_mask_lower_1 = np.array([0, lower_sat, lower_val], np.uint8)
red_mask_upper_1 = np.array([15, upper_sat, upper_val], np.uint8)
red_mask_lower_2 = np.array([165, lower_sat, lower_val], np.uint8)
red_mask_upper_2 = np.array([179, upper_sat, upper_val], np.uint8)

# BLUE
blue_mask_lower = np.array([105, lower_sat, lower_val], np.uint8)
blue_mask_upper = np.array([125, upper_sat, upper_val], np.uint8)

# WHITE (sat 0-110, all other colors start at 110; val 175-255 removes noise)
white_mask_lower = np.array([0, 0, 175], np.uint8)
white_mask_upper = np.array([179, lower_sat, upper_val], np.uint8)

# GREEN
green_mask_lower = np.array([45, lower_sat, lower_val], np.uint8)
green_mask_upper = np.array([85, upper_sat, upper_val], np.uint8)

# ORANGE
orange_mask_lower = np.array([15, lower_sat, lower_val], np.uint8)
orange_mask_upper = np.array([22, upper_sat, upper_val], np.uint8)

# YELLOW
yellow_mask_lower = np.array([22, lower_sat, lower_val], np.uint8)
yellow_mask_upper = np.array([33, upper_sat, upper_val], np.uint8)

# CYAN
cyan_mask_lower = np.array([85, lower_sat, lower_val], np.uint8)
cyan_mask_upper = np.array([105, upper_sat, upper_val], np.uint8)

# VIOLET
violet_mask_lower = np.array([125, lower_sat, lower_val], np.uint8)
violet_mask_upper = np.array([140, upper_sat, upper_val], np.uint8)

# MAGENTA
magenta_mask_lower = np.array([140, lower_sat, lower_val], np.uint8)
magenta_mask_upper = np.array([155, upper_sat, upper_val], np.uint8)

# PURPLE
purple_mask_lower = np.array([155, lower_sat, lower_val], np.uint8)
purple_mask_upper = np.array([165, upper_sat, upper_val], np.uint8)


def detect_color_in_bounding_box(image_np, current_box, used_normalized_coordinates):
    image = image_np.copy()
    top, left, bottom, right = current_box
    # adjust coordinates:
    if used_normalized_coordinates:
        (top, left, bottom, right) = get_box_coordinates_from_normalized_coordinates(
            current_box, image.shape[0], image.shape[1]
        )

    # coordinates corresponding to the center 50% of the bounding box surface area
    y = int(top + (bottom - top) * 0.25)
    h = int(top + (bottom - top) * 0.75)
    x = int(left + (right - left) * 0.25)
    w = int(left + (right - left) * 0.75)

    # crop image to center of current bounding box
    cropped_img = image[y:h, x:w]

    # TRANSFORMATION to remove noise
    kernel = np.ones((5, 5), np.uint8)
    img_dilation = cv2.dilate(cropped_img, kernel, iterations=2)
    img_dilated_and_eroded = cv2.erode(img_dilation, kernel, iterations=2)

    # HSV based frame
    hsv_frame = cv2.cvtColor(img_dilated_and_eroded, cv2.COLOR_BGR2HSV)

    # MASKS
    red_mask_1 = cv2.inRange(hsv_frame, red_mask_lower_1, red_mask_upper_1)
    red_mask_2 = cv2.inRange(hsv_frame, red_mask_lower_2, red_mask_upper_2)
    blue_mask = cv2.inRange(hsv_frame, blue_mask_lower, blue_mask_upper)
    white_mask = cv2.inRange(hsv_frame, white_mask_lower, white_mask_upper)
    green_mask = cv2.inRange(hsv_frame, green_mask_lower, green_mask_upper)
    orange_mask = cv2.inRange(hsv_frame, orange_mask_lower, orange_mask_upper)
    yellow_mask = cv2.inRange(hsv_frame, yellow_mask_lower, yellow_mask_upper)
    cyan_mask = cv2.inRange(hsv_frame, cyan_mask_lower, cyan_mask_upper)
    violet_mask = cv2.inRange(hsv_frame, violet_mask_lower, violet_mask_upper)
    magenta_mask = cv2.inRange(hsv_frame, magenta_mask_lower, magenta_mask_upper)
    purple_mask = cv2.inRange(hsv_frame, purple_mask_lower, purple_mask_upper)

    masks = [
        (red_mask_1, "RED"),
        (red_mask_2, "RED"),
        (blue_mask, "BLUE"),
        (white_mask, "WHITE"),
        (green_mask, "GREEN"),
        (orange_mask, "ORANGE"),
        (yellow_mask, "YELLOW"),
        (cyan_mask, "CYAN"),
        (violet_mask, "VIOLET"),
        (magenta_mask, "MAGENTA"),
        (purple_mask, "PURPLE"),
    ]

    # loop over masks and get corresponding color for bounding box
    object_color = "UNDECIDED"
    for mask in masks:
        if np.count_nonzero(mask[0]) > (mask[0].size * 0.5):
            object_color = mask[1]

    return object_color

# Filter methods

In [ ]:

# params
#boxes = detections['detection_boxes']
#classes = detections['detection_classes']+label_id_offset
#scores = detections['detection_scores']
def filter_detections_by_score(boxes, classes, scores, min_score_thresh):
    
    # Create an empty (boolean) list for filtering detections
    filter_arr = []
    
    # boxes: [N,4], N = number of boxes
    for i in range(boxes.shape[0]):
        if scores[i] > min_score_thresh:
            filter_arr.append(True)
        else:
            filter_arr.append(False)
    
    # detections above min score threshold
    filtered_boxes = boxes[filter_arr]
    filtered_classes = classes[filter_arr]
    filtered_scores = scores[filter_arr]
        
    return (filtered_boxes, filtered_classes, filtered_scores)


# params
#boxes = detections['detection_boxes']
#classes = detections['detection_classes']+label_id_offset
#scores = detections['detection_scores']
def filter_detections_by_class(boxes, classes, scores, category_index):
    
    # Create an empty (boolean) list for filtering detections
    filter_arr_WerkStueck = []
    
    # boxes: [N,4], N = number of boxes
    for i in range(boxes.shape[0]):
        if category_index[classes[i]]['name'] == "WerkStueck":
            filter_arr_WerkStueck.append(True)
        else:
            filter_arr_WerkStueck.append(False)
    
    # flip WerkStueck boolean filter list
    filter_arr_Behaelter = [not elem for elem in filter_arr_WerkStueck]
    
    filtered_WerkStueck_boxes = boxes[filter_arr_WerkStueck]
    filtered_WerkStueck_classes = classes[filter_arr_WerkStueck]
    filtered_WerkStueck_scores = scores[filter_arr_WerkStueck]
    
    filtered_Behaelter_boxes = boxes[filter_arr_Behaelter]
    filtered_Behaelter_classes = classes[filter_arr_Behaelter]
    filtered_Behaelter_scores = scores[filter_arr_Behaelter]
    
    filtered_WerkStueck_detections = (filtered_WerkStueck_boxes, filtered_WerkStueck_classes, filtered_WerkStueck_scores)
    filtered_Behaelter_detections = (filtered_Behaelter_boxes, filtered_Behaelter_classes, filtered_Behaelter_scores)
    
    return (filtered_WerkStueck_detections, filtered_Behaelter_detections)


# Visualization
@override visualization_utils.visualize_boxes_and_labels_on_image_array
Modified version - removed all unnecessary parts

In [ ]:
import collections
from object_detection.utils import visualization_utils as viz_utils
import six

STANDARD_COLORS = viz_utils.STANDARD_COLORS


def visualize_boxes_and_labels_on_image_array_overridden_short(
    image,
    boxes,
    classes,
    scores,
    category_index,
    visualize_werkstueck,
    use_normalized_coordinates=False,
    max_boxes_to_draw=20,
    min_score_thresh=0.5,
    agnostic_mode=False,
    line_thickness=4,
    mask_alpha=0.4,
    groundtruth_box_visualization_color="black",
    skip_boxes=False,
    skip_scores=False,
    skip_labels=False,
):

    """Args:
    image: uint8 numpy array with shape (img_height, img_width, 3)
    boxes: a numpy array of shape [N, 4]
    classes: a numpy array of shape [N]. Note that class indices are 1-based,
      and match the keys in the label map.
    scores: a numpy array of shape [N] or None.  If scores=None, then
      this function assumes that the boxes to be plotted are groundtruth
      boxes and plot all boxes as black with no classes or scores.
    category_index: a dict containing category dictionaries (each holding
      category index `id` and category name `name`) keyed by category indices.
    visualize_werkstueck: whether to skip visualizing WerkStueck class
    use_normalized_coordinates: whether boxes is to be interpreted as
      normalized coordinates or not.
    max_boxes_to_draw: maximum number of boxes to visualize.  If None, draw
      all boxes.
    min_score_thresh: minimum score threshold for a box or keypoint to be
      visualized.
    agnostic_mode: boolean (default: False) controlling whether to evaluate in
      class-agnostic mode or not.  This mode will display scores but ignore
      classes.
    line_thickness: integer (default: 4) controlling line width of the boxes.
    mask_alpha: transparency value between 0 and 1 (default: 0.4).
    groundtruth_box_visualization_color: box color for visualizing groundtruth
      boxes
    skip_boxes: whether to skip the drawing of bounding boxes.
    skip_scores: whether to skip score when drawing a single detection
    skip_labels: whether to skip label when drawing a single detection
    uint8 numpy array with shape (img_height, img_width, 3) with overlaid boxes.
    """
    hochregallager = Hochregallager()

    # filter detections by min score and classes
    boxes, classes, scores = filter_detections_by_score(
        boxes, classes, scores, min_score_thresh
    )
    (
        filtered_WerkStueck_detections,
        filtered_Behaelter_detections,
    ) = filter_detections_by_class(boxes, classes, scores, category_index)

    # by default only visualize 'Behaelter'
    if not visualize_werkstueck:
        boxes, classes, scores = filtered_Behaelter_detections

    box_to_display_str_map = collections.defaultdict(list)
    box_to_color_map = collections.defaultdict(str)
    for i in range(boxes.shape[0]):
        if max_boxes_to_draw == len(box_to_color_map):
            break
        box = tuple(boxes[i].tolist())
        if scores is None:
            box_to_color_map[box] = groundtruth_box_visualization_color
        else:
            display_str = ""
            if not skip_labels:
                if not agnostic_mode:
                    if classes[i] in six.viewkeys(category_index):
                        class_name = category_index[classes[i]]["name"]
                    else:
                        class_name = "N/A"
                    display_str = str(class_name)
                if category_index[classes[i]]["name"] == "Behaelter":
                    behaelter = Behaelter(
                        image, box, scores[i], filtered_WerkStueck_detections
                    )
                    hochregallager.add_behaelter(behaelter)
                    if not behaelter.empty:
                        display_str = "{}(filled, {})".format(
                            display_str, behaelter.werk_stueck.color
                        )
                if category_index[classes[i]]["name"] == "WerkStueck":
                    wkstk_color = detect_color_in_bounding_box(
                        image, box, use_normalized_coordinates
                    )
                    display_str = "{}(Color:{})".format(display_str, wkstk_color)
            if not skip_scores:
                if not display_str:
                    display_str = "{}%".format(round(100 * scores[i]))
                else:
                    display_str = "{}: {}%".format(display_str, round(100 * scores[i]))
            box_to_display_str_map[box].append(display_str)
            if agnostic_mode:
                box_to_color_map[box] = "DarkOrange"
            else:
                box_to_color_map[box] = STANDARD_COLORS[
                    classes[i] % len(STANDARD_COLORS)
                ]

    # Draw all boxes onto image.
    for box, color in box_to_color_map.items():
        ymin, xmin, ymax, xmax = box
        viz_utils.draw_bounding_box_on_image_array(
            image,
            ymin,
            xmin,
            ymax,
            xmax,
            color=color,
            thickness=0 if skip_boxes else line_thickness,
            display_str_list=box_to_display_str_map[box],
            use_normalized_coordinates=use_normalized_coordinates,
        )

    return image

# Detect in Real-Time

In [ ]:
category_index = label_map_util.create_category_index_from_labelmap(
    ANNOTATION_PATH + "/label_map.pbtxt"
)

In [ ]:
# Setup capture
#cap = cv2.VideoCapture(0)
#width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
#height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

In [ ]:
import cv2

ar_det = cv2.aruco.



img = "IMG_20220617_094458"
frame = cv2.imread("Tensorflow/workspace/images/train/{}.jpg".format(img))

# convert the image to grayscale format
img_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.imshow('gray image', cv2.resize(img_gray, (1500, 1200)))

# apply binary thresholding
ret, thresh = cv2.threshold(img_gray, 150, 255, cv2.THRESH_BINARY)

# detect the contours on the binary image using cv2.CHAIN_APPROX_NONE
contours, hierarchy = cv2.findContours(image=thresh, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_NONE)                                    
# draw contours on the original image
image_copy = frame.copy()
cv2.drawContours(image=image_copy, contours=contours, contourIdx=-1, color=(0, 255, 0), thickness=2, lineType=cv2.LINE_AA)              
# see the results
cv2.imshow('None approximation', cv2.resize(image_copy, (1500, 1200)))
cv2.waitKey(0)
cv2.imwrite('contours_none_image1.jpg', image_copy)
cv2.destroyAllWindows()







In [2]:
!pip uninstall opencv-python

^C


In [ ]:
img = "IMG_20220617_094458"
frame = cv2.imread("Tensorflow/workspace/images/train/{}.jpg".format(img))

# ret, frame = cap.read()
image_np = np.array(frame)

input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.float32)
detections = detect_fn(input_tensor)

num_detections = int(detections.pop("num_detections"))
detections = {
    key: value[0, :num_detections].numpy() for key, value in detections.items()
}
detections["num_detections"] = num_detections

# detection_classes should be ints.
detections["detection_classes"] = detections["detection_classes"].astype(np.int64)


image_np_with_detections = image_np.copy()


# min score for bounding boxes
min_score_threshold = 0.6


label_id_offset = 1
image_np_with_detections = image_np.copy()

visualize_boxes_and_labels_on_image_array_overridden_short(
    image_np_with_detections,
    detections["detection_boxes"],
    detections["detection_classes"] + label_id_offset,
    detections["detection_scores"],
    category_index,
    visualize_werkstueck=False,
    use_normalized_coordinates=True,
    max_boxes_to_draw=20,
    min_score_thresh=min_score_threshold,
    agnostic_mode=False,
)

cv2.imshow("object detection", cv2.resize(image_np_with_detections, (1500, 1200)))
cv2.waitKey(0)


# if cv2.waitKey(1) & 0xFF == ord('q'):
#     cap.release()
#     break

In [ ]:
import cv2.aruco